import { ROUTES } from './routes';
import { MESSAGES } from './messages';

export const MENU_ITEMS = [
  {
    id: 'dashboard',
    label: MESSAGES.MENU_DASHBOARD,
    href: ROUTES.DASHBOARD,
    icon: 'LayoutDashboard',
  },
  {
    id: 'prices',
    label: MESSAGES.MENU_PRICES,
    href: ROUTES.PRICES,
    icon: 'Activity',
  },
  {
    id: 'stocks',
    label: MESSAGES.MENU_STOCKS,
    href: ROUTES.STOCKS,
    icon: 'Package',
  },
  {
    id: 'transactions',
    label: MESSAGES.MENU_TRANSACTIONS,
    href: ROUTES.TRANSACTIONS,
    icon: 'ArrowLeftRight',
  },
  {
    id: 'suppliers',
    label: MESSAGES.MENU_SUPPLIERS,
    href: ROUTES.SUPPLIERS,
    icon: 'Truck',
  },
  {
    id: 'purchases',
    label: MESSAGES.MENU_PURCHASES,
    href: ROUTES.PURCHASES,
    icon: 'Boxes',
  },
  {
    id: 'customers',
    label: MESSAGES.MENU_CUSTOMERS,
    href: ROUTES.CUSTOMERS,
    icon: 'UserCheck',
  },
  {
    id: 'loyalty',
    label: 'Sadakat & RFM',
    href: ROUTES.LOYALTY,
    icon: 'HeartHandshake',
  },
  {
    id: 'crm',
    label: 'CRM & Kampanyalar',
    href: ROUTES.CRM,
    icon: 'MessageSquareShare',
  },
  {
    id: 'quotes',
    label: 'Teklif & İskonto',
    href: ROUTES.QUOTES,
    icon: 'BadgePercent',
  },
  {
    id: 'installments',
    label: MESSAGES.MENU_INSTALLMENTS,
    href: ROUTES.INSTALLMENTS,
    icon: 'CalendarClock',
  },
  {
    id: 'invoices',
    label: MESSAGES.MENU_INVOICES,
    href: ROUTES.INVOICES,
    icon: 'ReceiptText',
  },
  {
    id: 'expense-vouchers',
    label: 'Gider Pusulası',
    href: ROUTES.EXPENSE_VOUCHERS,
    icon: 'FileText',
  },
  {
    id: 'workshop',
    label: MESSAGES.MENU_WORKSHOP,
    href: ROUTES.WORKSHOP,
    icon: 'Flame',
  },
  {
    id: 'services',
    label: 'Servis & Tamir',
    href: ROUTES.SERVICES,
    icon: 'Wrench',
  },
  {
    id: 'branches',
    label: 'Şube Yönetimi',
    href: ROUTES.BRANCHES,
    icon: 'GitFork',
  },
  {
    id: 'transfers',
    label: 'Şube Transfer',
    href: ROUTES.TRANSFERS,
    icon: 'ArrowRightLeft',
  },
  {
    id: 'z-report',
    label: MESSAGES.MENU_Z_REPORT,
    href: ROUTES.Z_REPORT,
    icon: 'Building',
  },
  {
    id: 'balance-sheet',
    label: MESSAGES.MENU_BALANCE_SHEET,
    href: ROUTES.BALANCE_SHEET,
    icon: 'TrendingUp',
  },
  {
    id: 'executive-analytics',
    label: 'Yönetici & Tahmin',
    href: ROUTES.EXECUTIVE_ANALYTICS,
    icon: 'LineChart',
  },
  {
    id: 'approvals',
    label: 'Onay & Yetki',
    href: ROUTES.APPROVALS,
    icon: 'ShieldCheck',
  },
  {
    id: 'stock-audit',
    label: MESSAGES.MENU_STOCK_AUDIT,
    href: ROUTES.STOCK_AUDIT,
    icon: 'ClipboardCheck',
  },
  {
    id: 'rfid-stocktake',
    label: 'RFID Vitrin Sayımı',
    href: ROUTES.RFID_STOCKTAKE,
    icon: 'Radio',
  },
  {
    id: 'channels',
    label: 'Pazaryeri & E-Ticaret',
    href: ROUTES.CHANNELS,
    icon: 'Globe',
  },
  {
    id: 'data-hub',
    label: MESSAGES.MENU_DATA_HUB,
    href: ROUTES.DATA_HUB,
    icon: 'FileSpreadsheet',
  },
  {
    id: 'alerts',
    label: MESSAGES.MENU_ALERTS,
    href: ROUTES.ALERTS,
    icon: 'BellRing',
  },
  {
    id: 'ai-assistant',
    label: MESSAGES.MENU_AI_ASSISTANT,
    href: ROUTES.AI_ASSISTANT,
    icon: 'Bot',
  },
  {
    id: 'settings-ai',
    label: MESSAGES.MENU_SETTINGS_AI,
    href: ROUTES.SETTINGS_AI,
    icon: 'Settings',
  },
  {
    id: 'logs',
    label: MESSAGES.MENU_LOGS,
    href: ROUTES.LOGS,
    icon: 'History',
  },
  {
    id: 'price-check',
    label: MESSAGES.MENU_PRICE_CHECK,
    href: ROUTES.PRICE_CHECK,
    icon: 'ScanBarcode',
  },
  {
    id: 'users',
    label: MESSAGES.MENU_USERS,
    href: ROUTES.USERS,
    icon: 'Users',
  },
] as const;

