import { USER_ROLES, UserRole } from './roles';

// Atomik İzin Sabitleri — Magic String kontrolü gereği tüm yetkiler burada tanımlanır
export const PERMISSIONS = {
  // Gösterge & Fiyatlar
  DASHBOARD_READ: 'dashboard:read',
  PRICES_READ: 'prices:read',
  PRICES_MANAGE: 'prices:manage',

  // Stok
  STOCKS_READ: 'stocks:read',
  STOCKS_WRITE: 'stocks:write',
  STOCKS_DELETE: 'stocks:delete',
  
  // Alış/Satış & İşlemler
  TRANSACTIONS_READ: 'transactions:read',
  TRANSACTIONS_CREATE: 'transactions:create',
  TRANSACTIONS_REVISE: 'transactions:revise',
  
  // Müşteri & Veresiye
  CUSTOMERS_READ: 'customers:read',
  CUSTOMERS_WRITE: 'customers:write',
  CUSTOMERS_DEPOSITS: 'customers:deposits',
  
  // Toptancı
  SUPPLIERS_READ: 'suppliers:read',
  SUPPLIERS_WRITE: 'suppliers:write',
  SUPPLIERS_TRANSACT: 'suppliers:transact',
  
  // Kasa & Z-Raporu
  CASH_READ: 'cash:read',
  CASH_MOVE: 'cash:move',
  CASH_CLOSE: 'cash:close',
  
  // Fatura & e-Arşiv
  INVOICES_READ: 'invoices:read',
  INVOICES_ISSUE: 'invoices:issue',
  INVOICES_CANCEL: 'invoices:cancel',
  
  // Taksit & Senet
  INSTALLMENTS_READ: 'installments:read',
  INSTALLMENTS_CREATE: 'installments:create',
  INSTALLMENTS_PAY: 'installments:pay',
  
  // Hurda & Atölye
  WORKSHOP_READ: 'workshop:read',
  WORKSHOP_CREATE: 'workshop:create',
  WORKSHOP_COMPLETE: 'workshop:complete',
  
  // Sistem Yönetimi, Şube & Güvenlik
  USERS_MANAGE: 'users:manage',
  BRANCHES_MANAGE: 'branches:manage',
  SETTINGS_MANAGE: 'settings:manage',
  AUDIT_READ: 'audit:read',
  BACKUP_MANAGE: 'backup:manage',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Rol bazlı varsayılan izin matrisi
export const ROLE_PERMISSIONS_MAP: Record<UserRole, PermissionKey[]> = {
  [USER_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  
  [USER_ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PRICES_READ,
    PERMISSIONS.PRICES_MANAGE,
    PERMISSIONS.STOCKS_READ,
    PERMISSIONS.STOCKS_WRITE,
    PERMISSIONS.STOCKS_DELETE,
    PERMISSIONS.TRANSACTIONS_READ,
    PERMISSIONS.TRANSACTIONS_CREATE,
    PERMISSIONS.TRANSACTIONS_REVISE,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_WRITE,
    PERMISSIONS.CUSTOMERS_DEPOSITS,
    PERMISSIONS.SUPPLIERS_READ,
    PERMISSIONS.SUPPLIERS_WRITE,
    PERMISSIONS.SUPPLIERS_TRANSACT,
    PERMISSIONS.CASH_READ,
    PERMISSIONS.CASH_MOVE,
    PERMISSIONS.CASH_CLOSE,
    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.INVOICES_ISSUE,
    PERMISSIONS.INVOICES_CANCEL,
    PERMISSIONS.INSTALLMENTS_READ,
    PERMISSIONS.INSTALLMENTS_CREATE,
    PERMISSIONS.INSTALLMENTS_PAY,
    PERMISSIONS.WORKSHOP_READ,
    PERMISSIONS.WORKSHOP_CREATE,
    PERMISSIONS.WORKSHOP_COMPLETE,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.BRANCHES_MANAGE,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.BACKUP_MANAGE,
  ],

  [USER_ROLES.USER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PRICES_READ,
    PERMISSIONS.STOCKS_READ,
    PERMISSIONS.STOCKS_WRITE,
    PERMISSIONS.TRANSACTIONS_READ,
    PERMISSIONS.TRANSACTIONS_CREATE,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_WRITE,
    PERMISSIONS.CUSTOMERS_DEPOSITS,
    PERMISSIONS.SUPPLIERS_READ,
    PERMISSIONS.CASH_READ,
    PERMISSIONS.CASH_MOVE,
    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.INVOICES_ISSUE,
    PERMISSIONS.INSTALLMENTS_READ,
    PERMISSIONS.INSTALLMENTS_CREATE,
    PERMISSIONS.INSTALLMENTS_PAY,
    PERMISSIONS.WORKSHOP_READ,
    PERMISSIONS.WORKSHOP_CREATE,
  ],

  [USER_ROLES.TABLET]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PRICES_READ,
    PERMISSIONS.STOCKS_READ,
    PERMISSIONS.TRANSACTIONS_READ,
    PERMISSIONS.TRANSACTIONS_CREATE,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.INSTALLMENTS_READ,
  ],

  [USER_ROLES.PC]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PRICES_READ,
    PERMISSIONS.STOCKS_READ,
    PERMISSIONS.TRANSACTIONS_READ,
  ],
};
