// Route sabitleri — Magic String kuralı gereği tüm yollar burada
export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  PRICES: '/prices',
  USERS: '/users',
  STOCKS: '/stocks',
  TRANSACTIONS: '/transactions',
  SUPPLIERS: '/suppliers',
  PRICE_CHECK: '/price-check',
  CUSTOMERS: '/customers',
  LOGS: '/logs',
  API_AUTH: '/api/auth',
  API_USERS: '/api/users',
  API_STOCKS: '/api/stocks',
  API_TRANSACTIONS: '/api/transactions',
  API_SUPPLIERS: '/api/suppliers',
  API_SUPPLIER_TRANSACTIONS: '/api/supplier-transactions',
  API_CUSTOMERS: '/api/customers',
  API_CUSTOMER_TRANSACTIONS: '/api/customer-transactions',
  API_LOGS: '/api/logs',
  API_PRICES_LIVE: '/api/prices/live',
  API_DEALERS: '/api/dealers',
} as const;
