// Route sabitleri — Magic String kuralı gereği tüm yollar burada
export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  PRICES: '/prices',
  USERS: '/users',
  STOCKS: '/stocks',
  TRANSACTIONS: '/transactions',
  SUPPLIERS: '/suppliers',
  PRICE_CHECK: '/price-check',
  CUSTOMERS: '/customers',
  LOGS: '/logs',
  SHOWCASE: '/showcase',
  Z_REPORT: '/z-report',
  BALANCE_SHEET: '/balance-sheet',
  STOCK_AUDIT: '/stock-audit',
  DATA_HUB: '/data-hub',
  ALERTS: '/alerts',
  API_AUTH: '/api/auth',
  API_USERS: '/api/users',
  API_STOCKS: '/api/stocks',
  API_STOCKS_ANALYTICS: '/api/stocks/analytics',
  API_STOCKS_REORDER: '/api/stocks/reorder',
  API_TRANSACTIONS: '/api/transactions',
  API_SUPPLIERS: '/api/suppliers',
  API_SUPPLIER_TRANSACTIONS: '/api/supplier-transactions',
  API_CUSTOMERS: '/api/customers',
  API_CUSTOMER_TRANSACTIONS: '/api/customer-transactions',
  API_LOGS: '/api/logs',
  API_PRICES_LIVE: '/api/prices/live',
  API_DEALERS: '/api/dealers',
  API_Z_REPORT: '/api/z-report',
  API_Z_REPORT_SESSION: '/api/z-report/session',
  API_Z_REPORT_SUMMARY: '/api/z-report/summary',
  API_Z_REPORT_PRINT: '/api/z-report/print',
  API_ALERTS: '/api/alerts',
  API_BALANCE_SHEET: '/api/analytics/balance-sheet',
  API_STOCK_AUDIT: '/api/stocks/audit',
  API_BACKUP_EXPORT: '/api/backup/export',
  API_BACKUP_IMPORT: '/api/backup/import',
  AI_ASSISTANT: '/ai-assistant',
  SETTINGS_AI: '/settings/ai',
  API_AI_CHAT: '/api/ai/chat',
  API_AI_BRIEFING: '/api/ai/briefing',
  API_DEALER_AI_SETTINGS: '/api/dealer/ai-settings',
} as const;


